import type {NextPage} from 'next'
import {GetStaticProps} from 'next'
import IComment from "@interfaces/IComment";
import styled from "styled-components";
import {getContentFromSlug, HomePageCMSFields} from "../libs/pages";

interface HomePageProps {
    comments: IComment[] | null,
    matterData: HomePageCMSFields
}


export const getStaticProps: GetStaticProps<HomePageProps> = async _ => {
    const s = getContentFromSlug('home')
//   const contentDirectory = path.join(process.cwd(), 'content');
//    const fullPath = path.join(contentDirectory, "home" + ".md");
//    const pageData = fs.readFileSync(fullPath, "utf8");
//
//    const matterResult = matter(pageData, {
//        engines: {
//            yaml: (s) => yaml.load(s, {schema: yaml.JSON_SCHEMA}) as object
//        }
//    });
//
//    const matterData = matterResult.data as HomePageCMSFields;
//    matterData.fullPath = fullPath

    const comments = null
    return {
        notFound: false,
//        props: {comments: comments, matterData: matterData
        props: {
            comments: comments, matterData: s
        }
    }
}

const Home: NextPage<HomePageProps> = (props) => {
    console.log("props ", props)
    return <HomePageLayout>
        <PortraitWrapper><Img src={"/img/rw.png"} alt={""}/> </PortraitWrapper>
        <ArticleColumn><h1>{props.matterData.title}</h1>
            {props.matterData.body}
        </ArticleColumn>
    </HomePageLayout>
//    return (
//        <div className={styles.container}>
//            <Overview title={"test"}/>
//
//            <Head>
//                <title>Create Next App</title>
//                <meta name="description" content="Generated by create next app"/>
//                <link rel="icon" href="/favicon.ico"/>
//            </Head>
//            <Link href={"/nested/comment_page"}>COMMENT PAGE</Link>
//            <main className={styles.main}>
//                <h1 className={styles.title}>
//                    Welcome to <a href="https://nextjs.org">Next.js!</a>
//                </h1>
//                <p><label htmlFor={"test1"}>testing</label>
//                    <input type={"checkbox"} id={"test1"} name={"test1"}/></p>
//                <p className={styles.description}>
//
//                    Get started by editing{' '}
//                    <code className={styles.code}>pages/index.tsx</code>
//                </p>
//
//                <div className={styles.grid}>
//                    <a href="https://nextjs.org/docs" className={styles.card}>
//                        <h2>Documentation &rarr;</h2>
//                        <p>Find in-depth information about Next.js features and API.</p>
//                    </a>
//
//                    <a href="https://nextjs.org/learn" className={styles.card}>
//                        <h2>Learn &rarr;</h2>
//                        <p>Learn about Next.js in an interactive course with quizzes!</p>
//                    </a>
//
//                    <a
//                        href="https://github.com/vercel/next.js/tree/canary/examples"
//                        className={styles.card}
//                    >
//                        <h2>Examples &rarr;</h2>
//                        <p>Discover and deploy boilerplate example Next.js projects.</p>
//                    </a>
//
//                    <a
//                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//                        className={styles.card}
//                    >
//                        <h2>Deploy &rarr;</h2>
//                        <p>
//                            Instantly deploy your Next.js site to a public URL with Vercel.
//                        </p>
//                    </a>
//                </div>
//            </main>
//
//            <footer className={styles.footer}>
//                <a
//                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//                    target="_blank"
//                    rel="noopener noreferrer"
//                >
//                    Powered by{' '}
//                    <span className={styles.logo}>
//            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
//          </span>
//                </a>
//            </footer>
//        </div>
//    )
}

const ArticleColumn = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: flex-start;
  width: 100%;
  height: 100%;

  margin-bottom: auto;

  & > :not(h1,h2,h3,h4,h5,h6) {
    align-self: start;
    padding: 1rem;
  }
`


const Img = styled.img`

  width: 100%;
  height: 100%;
  border-radius: 10px;
`
const PortraitWrapper = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100%;
  width: 100%;
  //padding: 1.5em;
`
const HomePageLayout = styled.div`
  padding-top: 1em;
  width: 88vw;
  grid-gap: 1rem;
  display: grid;
  //grid-template-columns: 100%;
  //grid-template-rows: 100%;
  @media (min-width: 768px) {
    grid-template-columns: 66% 33%;
    grid-template-rows: auto ;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    height: 100%;
    //width: 100%;
  }
`
export default Home
